<?php include 'header.php'; ?>

<style>
	#logo {
		background: url("zhang_logo_research.png");
	}
</style>

<div id='content'>
	<h1>Why single-molecule biophysics?</h1>
	Structures and dynamics of cells are ultimately determined by numerous intra- and inter-molecular forces. Nevertheless, these forces are generally too weak to be directly detected in traditional bulk experiments. Our group has broad interests in measuring the forces that hold single proteins or protein-DNA complexes together and the forces that are generated by various molecular machines, as a crucial step to understand their biological functions. Our primary tool is high-resolution optical tweezers , which is capable of detecting the force and displacement change involved in the protein conformation transition at subnanometer and submillisecond resolution. In particular, we are focused on understanding the molecular mechanisms that underlie three important biological processes.
	<br>
	<br>
	<br>
	<h1>ATP-dependent chromatin remodeling by various remodeler complexes</h1>
	We have been testing the hypothesis that remodelers contain highly conserved DNA translocase engines by directly measuring their translocation processivity, velocity, step size and force generation. We are studying how the force is transduced to remodel chromatin structures in a tightly regulated manner. Finally, we are investigating how ATP-dependent remodeling activity is affected by histone modifications. Remodelers SWI/SNF and RSC are ATP- and nucleosome-dependent DNA translocases
	<p class='caption'>Zhang, Y.L., Smith, C.L., Saha, A., Grill, S.W., Mihardja, S., Smith, S.B., Cairns, B.R., Peterson, C.L., and Bustamantel, C. (2006). DNA translocation and loop formation mechanism of chromatin remodeling by SWI/SNF and RSC. Mol. Cell 24, 559-568</p>
	<p class='caption'>Saha, A., Wittmeyer, J., and Cairns, B.R. (2006). Chromatin remodelling: the industrial revolution of DNA around histones. Nat. Rev. Mol. Cell Biol. 7: 437-447</p>
	<br>
	<br>
	<h1>Regulated folding and assembly of SNARE proteins involved in membrane fusion</h1>
	SNARE proteins are the engines for membrane fusion. The current model for SNARE function suggests that these proteins generate forces to drive the fusion through an unusual protein zippering mechanism, by which a pair of cognate SNARE proteins (t- and v-SNAREs) progressively fold and assemble to form an extraordinarily stable four-helix bundle. This assembly process is controlled by numerous proteins that regulate the fusion in a spatially- and temporally-specific manner. We have undertaken to measure the force produced by a single pair of SNAREs and characterize how the force production is regulated by key regulatory proteins involved in neurotransmission. Besides SNAREs, We are also interested in protein folding in general.
	<p class='caption'>Jahn, R., and Scheller, R.H. (2006). SNAREs - engines for membrane fusion. Nat. Rev. Mol. Cell Biol. 7, 631-643</p>
	<p class='caption'>Sudhof, T.C., and Rothman, J.E. (2009). Membrane fusion: Grappling with SNARE and SM proteins. Science 323, 474-477</p>
	<p class='caption'>Giraudo, C.G., Garcia-Diaz, A., Eng, W.S., Chen, Y.H., Hendrickson, W.A., Melia, T.J., and Rothman, J.E. (2009). Alternative Zippering as an On-Off Switch for SNARE-Mediated Fusion. Science 323, 512-516</p>
	<br>
	<br>
	<h1>Membrane remodeling or fission mediated by dynamin and BAR proteins</h1>
	Dynamin has long been considered as a mechanochemical enzyme essential for endocytosis including neuronal endocytosis. But its mechanism of action remains controversial. The proposed models suggest that dynamin may twist, pinch, and/or stretch the membrane upon GTP hydrolysis in a concerted manner once many dynamin molecules coat on the membrane. We will characterize the underlying mechanosensing and mechanochemical transmission processes that lead to membrane deformation (such as tube formation) and eventually membrane fission.
	<p class='caption'>Roux, A, Uyhazi, K, Frost A, and De Camilli P. (2006). GTP-dependent twisting of dynamin implicates both constriction and tension in membrane fission. Nature 441: 528-531</p>
	<p class='caption'>Frost, A., Unger, V.M., and De Camilli, P. (2009). The BAR domain superfamily: Membrane-molding macromolecules. Cell 137: 191-196</p>
</div><!--end of content-->

</div><!--end of page-->
<?php include 'footer.php'; ?>
